---
title: "PubmedDB"
output: html_notebook
---

##PubMedDB

---
title: "Practicum 2"
output: html_notebook
---

```{r}
# 1. Library
library(RMySQL)
library(XML)
library(DBI)
library(knitr)
```

```{r}
# 2. Settings (Jordan's db)
db_user <- 'cs5200practicum2'
db_password <- 'tctvuje8'
db_name <- 'dbpracticum2'
db_host <- 'practicum2.cb9tzbdsyfxk.us-east-2.rds.amazonaws.com'
db_port <- 3306

# 3. Read data from db
mydb <-  dbConnect(MySQL(), user = db_user, password = db_password,
                 dbname = db_name, host = db_host, port = db_port)
```


```{r}
if (FALSE) {
# 2. Settings (Bob's db)
db_user2 <- 'CS5200'
db_password2 <- 'db2password'
db_name2 <- 'dbpracticum2'
db_host2 <- 'cs5200-practicum2.chwzgwg0nlr5.us-east-1.rds.amazonaws.com'
db_port2 <- 3306

# 3. Read data from db
mydb <-  dbConnect(MySQL(), user = db_user2, password = db_password2,
                 dbname = db_name2, host = db_host2, port = db_port2)
}
```


```{r jordans path}
path <- "C:/Users/jorda/Documents/CS_Masters/CS5200_Databases/Homework/Practicum2/"
fn <- "pubmed_sample.xml"
fpn = paste0(path, fn)
```

```{r bobs path}
if (FALSE) {
path <-"/Users/robert/Documents/CS5200/Practicum2/"
fn <- "pubmed_sample.xml"
fpn = paste0(path, fn)
}
```

```{r}
# Reading the XML file and parse into DOM
xmlDOM <- xmlParse(file = fpn)

# get the root node of the DOM tree
r <- xmlRoot(xmlDOM)
```

```{sql createTableAuthor, connection=mydb}
CREATE TABLE IF NOT EXISTS Author (
  author_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL
);
```

```{r}
Author.df <- data.frame (author_id = integer(),
                          first_name = character(),
                          last_name = character(),
                          stringsAsFactors = F)
```

```{sql createTableHistory, connection=mydb}
CREATE TABLE IF NOT EXISTS History (
  history_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_id INT NOT NULL,
  pub_status TEXT NOT NULL,
  year INT,
  month INT,
  day INT
);
```

```{r}
History.df <- data.frame (history_id = integer(),
                          article_id = integer(),
                          stringsAsFactors = F)
```

```{r}
HistoryStatus.df <- data.frame (status_id = integer(),
                          history_id = integer(),
                          pub_status = character(),
                          status_date = character(),
                          stringsAsFactors = F)
```

```{sql createTableJournal, connection=mydb}
CREATE TABLE IF NOT EXISTS Journal (
  journal_title TEXT PRIMARY KEY
);
```

```{r}
Journal.df <- data.frame (journal_title = character(),
                          stringsAsFactors = F)
```

```{sql createTableIssue, connection=mydb}
CREATE TABLE IF NOT EXISTS JournalIssue (
  issue_id INT PRIMARY KEY,
  journal_title TEXT NOT NULL,
  cited_medium TEXT NOT NULL,
  volume INT NOT NULL,
  issue INT NOT NULL,
  pub_date DATE NOT NULL,
  FOREIGN KEY (journal_title) REFERENCES Journal(journal_title)
  ON DELETE CASCADE,
);
```

```{r}
Issue.df <- data.frame (issue_id = integer(),
                        journal_title = character(),
                          cited_medium = character(),
                          volume = integer(),
                          issue = integer(),
                          pub_date_year = integer(),
                          pub_date_month = character(),
                          stringsAsFactors = F)
```


```{sql createTableArticle, connection=mydb}
CREATE TABLE IF NOT EXISTS Article (
  article_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  journal_title TEXT NOT NULL,
  article_title TEXT NOT NULL,
  FOREIGN KEY (journal_title) REFERENCES Journal(journal_title)
  ON DELETE CASCADE,
);
```

```{r}
numArticles <- xmlSize(r) 

Article.df <- data.frame (article_id = integer(),
                          journal_title = character(),
                          article_title = character(),
                          stringsAsFactors = F)
```

```{sql createTableAuthorJoin, connection=mydb}
CREATE TABLE IF NOT EXISTS AuthorJoin (
  author_id INT NOT NULL,
  article_id INT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES Author(author_id)
  ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES Article(article_id)
  ON DELETE CASCADE,
  PRIMARY KEY (author_id, article_id)
);
```

```{r}
AuthorJoin.df <- data.frame (author_id = integer(),
                          article_id = integer(),
                          stringsAsFactors = F)
```

```{r ParseAuthors}
parseAuthors <- function (anAuthorListNode)
{
  newAuthor.df <- data.frame (author_id = integer(),
                          first_name = character(),
                          last_name = character(),
                          stringsAsFactors = F)
  n <- xmlSize(anAuthorListNode)
  
  for (m in 1:n)
  {
    anAuthor <- anAuthorListNode[[m]]
    first_name <- xmlValue(anAuthor[[2]])
    last_name <- xmlValue(anAuthor[[1]])

    newAuthor.df[m,2] <- first_name
    newAuthor.df[m,3] <- last_name

  }

  return(newAuthor.df)
}
```


```{r ParseJournals}
parseJournals <- function (anArticle)
{
  newJournal.df <- Journal.df <- data.frame (journal_title = character(),
                          stringsAsFactors = F)

  #Getting Title
  titleeexp <-"./MedlineCitation/Article/Journal/Title"
  tempTitle <- xpathSApply(anArticle,titleeexp)
  title <- xmlValue(tempTitle)

  newJournal.df[1,1] <- title
  
  return(newJournal.df)
}
```

```{r Parse JournalIssue}
parseIssues <- function (anArticle)
{
  newIssue.df <- Issue.df <- data.frame (issue_id = integer(),
                        journal_title = character(),
                          cited_medium = character(),
                          volume = integer(),
                          issue = integer(),
                          pub_date_year = integer(),
                          pub_date_month = character(),
                          stringsAsFactors = F)

  #Getting Cited Medium
  CMexp <-"string(./MedlineCitation/Article/Journal/JournalIssue/@CitedMedium)"
  tempCM <- xpathSApply(anArticle,CMexp)
  cited_medium <- tempCM

  #Getting Volume
  volexp <-"./MedlineCitation/Article/Journal/JournalIssue/Volume"
  tempVolume <- xpathSApply(anArticle,volexp)
  volume <- xmlValue(tempVolume)
  
  # #Getting Issue
  issueexp <-"./MedlineCitation/Article/Journal/JournalIssue/Issue"
  tempIssue <- xpathSApply(anArticle,issueexp)
  issue <- xmlValue(tempIssue)
  
  #Getting PubDate information
  pubdateexp <- "./MedlineCitation/Article/Journal/JournalIssue/PubDate"
  tempPubDate <- xpathSApply(anArticle,pubdateexp)
  singlenode <- tempPubDate[[1]]
  childnodes <- xmlChildren(singlenode)
  
  year <- xmlValue(childnodes[1])
  month <- xmlValue(childnodes[2])

  #Getting Title
  titleeexp <-"./MedlineCitation/Article/Journal/Title"
  tempTitle <- xpathSApply(anArticle,titleeexp)
  title <- xmlValue(tempTitle)

  newIssue.df[1,2] <- title
  newIssue.df[1,3] <- cited_medium
  newIssue.df[1,4] <- volume
  newIssue.df[1,5] <- issue
  newIssue.df[1,6] <- year
  newIssue.df[1,7] <- month
  
  
  return(newIssue.df)
}

```



```{r ParseHistory}
parseHistory <- function (aHistoryNode, i)
{
  newHistory.df <- History.df <- data.frame (history_id = integer(),
                          article_id = integer(),
                          stringsAsFactors = F)
  newHistory.df[m,2] <- i
  
  n <- xmlSize(aHistoryNode)
  
  return(newHistory.df)
}
```

```{r ParseHistoryStatus}
parseHistoryStatus <- function (aHistoryNode, i)
{
  #newHistory.df[m,2] <- i
  
  n <- xmlSize(aHistoryNode)
  
  newHistoryStatus.df <- data.frame (status_id = integer(),
                      history_id = integer(),
                      pub_status = character(),
                      status_date = character(),
                      stringsAsFactors = F)
  
  for (m in 1:n)
  {
    aDateNode <- aHistoryNode[[m]]
    
    dateNodeAttributes <- xmlAttrs(aDateNode)
    pub_status <- as.character(dateNodeAttributes[1])

    hisYear <- as.character(xmlValue(aDateNode[[1]]))
    hisMonth <- as.character(xmlValue(aDateNode[[2]]))
    hisDay <- as.character(xmlValue(aDateNode[[3]]))
    
    hisDate <- paste(hisDay, hisMonth, hisYear, sep = "-")
    historystatusrow <- nrow(HistoryStatus.df) + 1
    
    newHistoryStatus.df[m,3] <- pub_status
    newHistoryStatus.df[m,4] <- hisDate
    
  }
  return(newHistoryStatus.df)
}
```

```{r}
r <- xmlRoot(xmlDOM)
#Iterate through the number of articles
for (i in 1:numArticles) #should be numArticles not 3
{
  #Get the next article node
  anArticle <- r[[i]]
  
  #Parse Author information, returns a data frame of the authors of an individual article
  authorNode <-"./MedlineCitation/Article/AuthorList/Author"
  xauth <- xpathSApply(anArticle,authorNode)
  newAuthor.df <- parseAuthors(xauth)
  
  #Adding the Authors to the Author.df
  tempAuthors <- Author.df
  Author.df <- rbind(tempAuthors, newAuthor.df)
  
  #Parse the journal node
  newJournal.df <- parseJournals(anArticle)
  journalNode <-"./MedlineCitation/Article/Journal"
  xjourn <- xpathSApply(anArticle,journalNode)
  
  journalTitleNode <-"./MedlineCitation/Article/Journal/Title"
  tempTitle <- xpathSApply(anArticle,journalTitleNode)
  journal_title <- xmlValue(tempTitle)
  
  #Adding the journals to the journal.df
  tempJournal <-Journal.df
  Journal.df <- rbind(tempJournal,newJournal.df)
  
  #Parse the issue node
  newIssue.df <- parseIssues(anArticle)
  
  #Adding the issues to the issue.df
  tempIssue <-Issue.df
  Issue.df <- rbind(tempIssue,newIssue.df)
  
  #Parse History information, returns a data frame of the history dates of an individual article
  #historyNode <-"./PubmedData/History/PubMedPubDate"
  #xhistory <- xpathSApply(anArticle,historyNode)
  #newHistory.df <- parseHistory(xhistory, i)
  
  #Adding the History to the History.df
  #tempHistory <-History.df
  #History.df <- rbind(tempHistory,newHistory.df)
  
  #Parse History Status
  historyStatusNode <-"./PubmedData/History/PubMedPubDate"
  xhistorystatus <- xpathSApply(anArticle,historyStatusNode)
  newHistoryStatus.df <- parseHistoryStatus(xhistorystatus, i)
  
  #Adding the Hisotry Status to the historystatus.df
  tempHistoryStatus <-HistoryStatus.df
  HistoryStatus.df <- rbind(tempHistoryStatus,newHistoryStatus.df)
  
  #Getting article title Node
  titleNode <-"./MedlineCitation/Article/ArticleTitle"
  xtitle <- xpathSApply(anArticle,titleNode)
  artTitle <- as.character(xmlValue(xtitle[1]))
  
  #Adding article title and article_id to data frame
  Article.df[i,3] <- artTitle
  Article.df[i,2] <- journal_title
  Article.df[i,1] <- i
}



#Delete Journal Duplicates
duplicateJournals <- Journal.df
Journal.df <- duplicateJournals[!duplicated(duplicateJournals),]

#Delete Issue Duplicates
duplicateIssues <- Issue.df
Issue.df <- duplicateIssues[!duplicated(duplicateIssues),]

#Delete Author Duplicates
duplicateAuthors <- Author.df
Author.df <- duplicateAuthors[!duplicated(duplicateAuthors),]

#Delete History Duplicates
duplicateHistory <- History.df
History.df <- duplicateHistory[!duplicated(duplicateHistory),]

#Delete HistoryStatus Duplicates
duplicateHistoryStatus <- HistoryStatus.df
HistoryStatus.df <- duplicateHistoryStatus[!duplicated(duplicateHistoryStatus),]

print(History.df)
print(HistoryStatus.df)
print(Author.df)
print(Journal.df)
print(Issue.df)
print(Article.df)

```

```{r Adding author_id}
num.authors <- nrow(Author.df)

for (r in 1:num.authors){
  Author.df$author_id[r] <- r
}

print(Author.df)
```

```{r Adding journal_id}
if(FALSE){
num.journals <- nrow(Journal.df)

for (r in 1:num.journals){
  Journal.df$journal_id[r] <- r
}
print(Journal.df)
}
```

```{r Adding status_id}
num.historystatus <- nrow(HistoryStatus.df)

for (r in 1:num.historystatus){
  HistoryStatus.df$status_id[r] <- r
}
print(HistoryStatus.df)
```

```{r Adding issue_id}
num.issue <- nrow(Issue.df)

for (r in 1:num.issue){
  Issue.df$issue_id[r] <- r
}
print(Issue.df)
```

```{r Link Journals}
print(num.journals)
r <- xmlRoot(xmlDOM)

for (i in 1:numArticles) {
  anArticle <- r[[i]]
  
  #Getting the journal title to compare to
  titleeexp <-"./MedlineCitation/Article/Journal/Title"
  tempTitle <- xpathSApply(anArticle,titleeexp)
  journaltitle <- xmlValue(tempTitle)

  volexp <-"./MedlineCitation/Article/Journal/JournalIssue/Volume"
  tempVolume <- xpathSApply(anArticle,volexp)
  volume <- xmlValue(tempVolume)
  
  #Getting Issue
  issueexp <-"./MedlineCitation/Article/Journal/JournalIssue/Issue"
  tempIssue <- xpathSApply(anArticle,issueexp)
  issue <- xmlValue(tempIssue)
  
  print(Journal.df$journal_title[j])
  print(journaltitle)
  
  for(j in 1:num.journals){
    if(Journal.df$journal_title[j] == journaltitle && Journal.df$volume[j] == volume && Journal.df$issue == issue){

        a <- j
        Article.df$journal_id[i] <- a
        print(a)
    }
  }
}
print(Article.df)
```

```{r Make AuthorJoin}
#New root
root <- xmlRoot(xmlDOM)

#go through each article
for ( i in 1:numArticles){
  
  #Gets an article
  anArticle <- root[[i]]

  #Parse Author list node
  authorNode <-"./MedlineCitation/Article/AuthorList/Author"
  xauth <- xpathApply(anArticle,authorNode)

  #size of authorlist
  n <- xmlSize(xauth)
  
  #finds the first name/last name of each author
  for (m in 1:n)
  {
    anAuthor <- xauth[[m]]
    first_name <- xmlValue(anAuthor[[2]])
    last_name <- xmlValue(anAuthor[[1]])

    #if the first name and last name match whats in the Author.df it adds the author_id and article_id to the table
    for( j in 1:num.authors) {
      if (Author.df$first_name[j] == first_name && Author.df$last_name[j] == last_name) {
        val <- Author.df$author_id[j]
        
        authorjoinrow <- nrow(AuthorJoin.df) + 1
        AuthorJoin.df[authorjoinrow,2] <- i
        AuthorJoin.df[authorjoinrow,1] <- val
      }
    }
  }
}
print(AuthorJoin.df)
```

```{r}
print(Article.df)
print(History.df)
print(HistoryStatus.df)
```


```{r Make History (join)}
#New root
root <- xmlRoot(xmlDOM)

#go through each article
for ( i in 1:numArticles){
  
  #Gets an article
  anArticle <- root[[i]]
  
  #Parse History information, returns a data frame of the history dates of an individual article
  historyNode <-"./PubmedData/History/PubMedPubDate"
  xhistory <- xpathSApply(anArticle,historyNode)

  #size of historyStatus
  n <- xmlSize(xhistory)
  
  #finds the first name/last name of each author
  for (m in 1:n)
  {
    aDateNode <- xhistory[[m]]
    
    dateNodeAttributes <- xmlAttrs(aDateNode)
    pub_status <- as.character(dateNodeAttributes[1])

    hisYear <- as.character(xmlValue(aDateNode[[1]]))
    hisMonth <- as.character(xmlValue(aDateNode[[2]]))
    hisDay <- as.character(xmlValue(aDateNode[[3]]))
    
    hisDate <- paste(hisDay, hisMonth, hisYear, sep = "-")

    #if the first name and last name match whats in the Author.df it adds the author_id and article_id to the table
    for( j in 1:num.historystatus) {
      if (HistoryStatus.df$pub_status[j] == pub_status && HistoryStatus.df$status_date[j] == hisDate) {
        val <- HistoryStatus.df$status_id[j]
        
        historystatusjoinrow <- nrow(History.df) + 1
        History.df[historystatusjoinrow,1] <- val
        History.df[historystatusjoinrow,2] <- i
      }
    }
  }
}

print(History.df)
```















```{r}
dbDisconnect(mydb)
```
